### ISSUE TITLE
make merge erros

### ISSUE THREAD

**Issue by auvipy** [JulienPalard/python-docs-cookiecutter#1]
make -C ../cpython//Doc/ VENVDIR=~/.venvs/python-docs-i18n/ PYTHON=/usr/bin/python3 venv
make[1]: *** ../cpython//Doc/: No such file or directory.  Stop.
make: *** [Makefile:44: upgrade_venv] Error 2

Should I have to modify some scripts paths? I don't use venv

**Comment by JulienPalard** [comment]
We upgraded the makefile on python-docs-fr, I just copied the modifications here, can you try again?

To get the new makefile, maybe replay the cookiecuter in a temporary directory and just copy the Makefile to your repository.

**Comment by auvipy** [comment]
OK

**Comment by JulienPalard** [comment]
Did it worked? Please reopen if needed.
