### ISSUE TITLE
make merge command gives errors.

### ISSUE THREAD

**Issue by OmerFI** [JulienPalard/python-docs-cookiecutter#6]
Hello, I had this issue:

![Error](https://user-images.githubusercontent.com/54645034/114445346-a5b0ca00-9bd8-11eb-93ae-0ea813450d41.png)

After that, I opened the MakeFile. I changed the BRANCH to 3.9 and I tried again:

![Error2](https://user-images.githubusercontent.com/54645034/114445804-2e2f6a80-9bd9-11eb-9427-2550f7e46c75.png)

After that:

![Error3](https://user-images.githubusercontent.com/54645034/114446015-6c2c8e80-9bd9-11eb-9f94-eaf454b2a112.png)

I just did all of the instructions given in the Readme file. And I haven't deleted anything. Could you help me?

**Comment by JulienPalard** [comment]
Yes I think I can help, let me review my README, it should be out of date.

**Comment by JulienPalard** [comment]
Can you please try again from scratch? We simplified our makefile a lot, a few weeks ago, and I forgot to merge it on this cookiecutter. Just did the upgrade.

**Comment by JulienPalard** [comment]
Beware I also updated the README as it's now mandatory to run the git init, switch branch, and make an initial commit before merging.

You may hit:

```
You're missing dependencies, please enable a venv and install:

  python -m pip install -r requirements.txt -r ../cpython//Doc/requirements.txt
```

which is expected if you don't already have a venv with all required dependencies installed.

**Comment by OmerFI** [comment]
I did all of the instructions given in the README file except the last instruction, but in the last instruction, there is a problem.
![error](https://user-images.githubusercontent.com/54645034/114609417-73ba6900-9ca7-11eb-8492-198a89ba4dd4.png)

**Comment by OmerFI** [comment]
Maybe, to make a gif can be good for anyone.

**Comment by JulienPalard** [comment]
Did you forgot the `make merge`? If not, what happened during it?

**Comment by OmerFI** [comment]
Sorry, I forgot the ```make merge```. After all I have this:

![Screenshot_4](https://user-images.githubusercontent.com/54645034/114623530-62f4fd80-9c7d-11eb-86e8-3ae371a22bb4.png)

Should I do anything else?

**Comment by JulienPalard** [comment]
This is the normal state yes.

The `make merge` gave you an hint on how to add only file that *really changed*: it's usefull when you merge, say monthly, to avoid a big commit of only po headers and no actual change in them.

Take a look at various translations if you want ideas on different possible workflows: https://github.com/python/?q=python-docs-&type=&language=&sort=

Here in France our workflow is basic: we just use github PRs. But other countries use online tools like transifex, pontoon, ..., as the PEP 545 say, use the workflow that fit the best, as long as we can `git clone` the `.po` files with the right hierarchy to build docs.python.org it's OK.

Don't hesitate to get us updated about the progression on docs at python dot org. You may want to team with https://github.com/alaeddingurel/python-docs-tr which also tried to start a Turkish translation a few years ago.

Anyway, don't translate alone, there's too much to do.

I'm closing this as the make merge now works, don't hesitate to continue the discussion on docs@ if you have any question.
